# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pyradise}
  s.version = "0.3.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcos Piccinini"]
  s.date = %q{2010-01-12}
  s.default_executable = %q{pyradise}
  s.email = %q{x@nofxx.com}
  s.executables = ["pyradise"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/pyradise",
     "lib/pyradise.rb",
     "lib/pyradise/cli.rb",
     "lib/pyradise/i18n.rb",
     "lib/pyradise/migrate.rb",
     "lib/pyradise/product.rb",
     "lib/stores.yml",
     "pyradise.gemspec",
     "script/console",
     "spec/pyradise/product_spec.rb",
     "spec/pyradise_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/nofxx/pyradise}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Paraguay gem!}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/pyradise_spec.rb",
     "spec/pyradise/product_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sequel>, [">= 0"])
    else
      s.add_dependency(%q<sequel>, [">= 0"])
    end
  else
    s.add_dependency(%q<sequel>, [">= 0"])
  end
end

